---
image: natanfelles/php-base

test:php:
  stage: test
  cache:
    paths:
      - vendor/
  before_script:
    - composer install
  script:
    # Run PHPUnit
    - vendor/bin/phpunit --colors=never
    # Run phpDocumentor
    - phpdoc
  artifacts:
    paths:
      - build/coverage/
      - build/docs/
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

pages:
  stage: deploy
  dependencies:
    - test:php
  environment:
    name: production
    url: https://the-framework.gitlab.io
  script:
    - mkdir public/
    - mv build/coverage/ public/
    - mv build/docs/ public/
    - curl -sS https://the-framework.gitlab.io/redirect.php | php
  artifacts:
    paths:
      - public
  only:
    - master
