---
image: natanfelles/php-base

test:php7.3:
  stage: test
  cache:
    paths:
      - vendor/
  before_script:
    - composer install
  script:
    # Run PHPUnit
    - vendor/bin/phpunit --colors=never
    # ApiGen
    #- vendor/bin/apigen generate src --destination build/api/
  artifacts:
    paths:
      - build/coverage/
      #- build/api/
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'

pages:
  stage: deploy
  dependencies:
    - test:php7.3
  environment:
    name: production
    url: https://the-framework.gitlab.io
  script:
    - mkdir public/
    - mv build/coverage/ public/
    #- mv build/api/ public/
    - curl -sS https://the-framework.gitlab.io/redirect.php | php
    - 'curl --request POST --header "PRIVATE-TOKEN: $BUILD_TOKEN" "https://gitlab.com/api/v4/projects/11395127/pipeline?ref=master"'
  artifacts:
    paths:
      - public
  only:
    - master
